import { Project, Skill, Experience } from '@/types';

export const projects: Project[] = [
  {
    id: '1',
    title: 'NeuralDash Analytics',
    description: 'A real-time analytics dashboard with AI-powered insights, interactive charts, and customizable widgets for monitoring business metrics.',
    tags: ['React', 'TypeScript', 'D3.js', 'Node.js'],
    liveUrl: '#',
    githubUrl: '#',
    featured: true,
    color: '#6c63ff',
  },
  {
    id: '2',
    title: 'TaskFlow Pro',
    description: 'A collaborative project management tool with kanban boards, time tracking, and team communication features built for remote teams.',
    tags: ['React', 'Redux', 'Socket.io', 'PostgreSQL'],
    liveUrl: '#',
    githubUrl: '#',
    featured: true,
    color: '#ff6b6b',
  },
  {
    id: '3',
    title: 'CryptoScan',
    description: 'A cryptocurrency portfolio tracker with live price feeds, profit/loss analysis, and smart portfolio rebalancing suggestions.',
    tags: ['Next.js', 'Chart.js', 'REST API', 'Tailwind'],
    liveUrl: '#',
    githubUrl: '#',
    featured: true,
    color: '#43e97b',
  },
  {
    id: '4',
    title: 'DevBlog CMS',
    description: 'A headless CMS built for developers, with markdown support, syntax highlighting, and a custom plugin ecosystem.',
    tags: ['Node.js', 'GraphQL', 'MongoDB', 'React'],
    liveUrl: '#',
    githubUrl: '#',
    featured: false,
    color: '#f7971e',
  },
  {
    id: '5',
    title: 'EcoTrack',
    description: 'A sustainability app that helps users track their carbon footprint and discover eco-friendly alternatives through ML recommendations.',
    tags: ['React Native', 'Python', 'TensorFlow', 'Firebase'],
    liveUrl: '#',
    githubUrl: '#',
    featured: false,
    color: '#56ccf2',
  },
  {
    id: '6',
    title: 'SoundWave Studio',
    description: 'A browser-based audio editor with multi-track recording, effects processing, and real-time collaboration for musicians.',
    tags: ['Web Audio API', 'WebRTC', 'React', 'Rust/WASM'],
    liveUrl: '#',
    githubUrl: '#',
    featured: false,
    color: '#f953c6',
  },
];

export const skills: Skill[] = [
  { name: 'React', level: 95, category: 'frontend' },
  { name: 'TypeScript', level: 90, category: 'frontend' },
  { name: 'Next.js', level: 85, category: 'frontend' },
  { name: 'CSS / SCSS', level: 88, category: 'frontend' },
  { name: 'Node.js', level: 82, category: 'backend' },
  { name: 'GraphQL', level: 75, category: 'backend' },
  { name: 'PostgreSQL', level: 78, category: 'backend' },
  { name: 'Python', level: 72, category: 'backend' },
  { name: 'Docker', level: 80, category: 'tools' },
  { name: 'Git', level: 92, category: 'tools' },
  { name: 'Figma', level: 70, category: 'tools' },
  { name: 'AWS', level: 68, category: 'tools' },
];

export const experiences: Experience[] = [
  {
    id: '1',
    company: 'Nexus Labs',
    role: 'Senior Frontend Engineer',
    period: '2022 – Present',
    description: 'Led the redesign of the core product dashboard, improving performance by 40% and user engagement by 60%. Mentored a team of 4 engineers and introduced component-driven architecture.',
    tags: ['React', 'TypeScript', 'Design Systems'],
  },
  {
    id: '2',
    company: 'Vercel (Contract)',
    role: 'Full-Stack Developer',
    period: '2021 – 2022',
    description: 'Built and maintained high-traffic Next.js applications for enterprise clients. Contributed to internal tooling that reduced deployment times by 35%.',
    tags: ['Next.js', 'Node.js', 'PostgreSQL'],
  },
  {
    id: '3',
    company: 'StartupHQ',
    role: 'Frontend Developer',
    period: '2019 – 2021',
    description: 'Developed responsive web applications from concept to launch for 15+ startup clients. Established a shared component library used across all projects.',
    tags: ['React', 'Vue.js', 'REST APIs'],
  },
  {
    id: '4',
    company: 'Freelance',
    role: 'Web Developer',
    period: '2017 – 2019',
    description: 'Worked with small businesses and creatives to build custom websites and e-commerce stores, handling everything from design to deployment.',
    tags: ['HTML/CSS', 'JavaScript', 'WordPress'],
  },
];
